target:
  image: ansible/centos7-ansible:stable
  container_name: ansible_target
  expose:
    - "22"
  volumes:
    - ~/.ssh/id_rsa.pub:/root/.ssh/authorized_keys
  privileged: true

test:
  build:
    context: .
    dockerfile: ./ansible.Dockerfile
  links:
    - target
  volumes:
    - ~/.ssh/id_rsa:/root/.ssh/id_rsa
    - ~/.ssh/id_rsa.pub:/root/.ssh/id_rsa.pub
    - .:/ansible/playbooks
